services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      # Recommended volume for FreshRSS persistent data such as configuration and SQLite databases
      - /srv/ssd/freshrss/data:/var/www/FreshRSS/data
      # Optional volume for storing third-party extensions
      - /srv/ssd/freshrss/extensions:/var/www/FreshRSS/extensions
      # Optional file providing custom global settings (used before a FreshRSS install)
      - ./config.custom.php:/var/www/FreshRSS/data/config.custom.php
      # Optional file providing custom user settings (used before a new user is created)
      - ./config-user.custom.php:/var/www/FreshRSS/data/config-user.custom.php
    env_file:
      - public.env
      - private.env
    networks:
      - caddy-proxy
      - freshrss-internal
      - freshrss-internet
  freshrss-db:
    image: postgres:17
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - /srv/ssd/freshrss/db:/var/lib/postgresql/data
    env_file:
      - public.env
      - private.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_BASE}
      POSTGRES_USER: ${DB_USER}
    networks:
      - freshrss-internal

networks:
  caddy-proxy:
    external: true
  freshrss-internal:
    internal: true
  freshrss-internet:
